### ISSUE TITLE
Default behaviour for 403 answer seems to be DoS of ZyteAPI

### ISSUE THREAD

**Issue by IvanVas** [zytedata/python-zyte-api#6]
By default, if the client gets 403 from ZyteAPI it continues to retry. This can create unnecessary load on the API.

Relevant code: https://github.com/zytedata/python-zyte-api/blob/main/zyte_api/__main__.py#L43

**Comment by BurnzZ** [comment]
After some offline discussions, it would seem that the Request-level errors aren't retried: https://github.com/zytedata/python-zyte-api/blob/main/zyte_api/aio/retry.py#L45-L49

**Comment by Gallaecio** [comment]
Shall we close then?

**Comment by BurnzZ** [comment]
@Gallaecio , thanks for reminding me. Yep, we can close this one out.
